/**:
  ros__parameters:
    plugin_denylist:
      # common

      # extras
      - image_pub
      - vibration
      - rangefinder
      - wheel_odometry

    plugin_allowlist:
      - distance_sensor

    #   - 'sys_*'
